spring.application.name=explore-openai

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3
spring.ai.ollama.completion.model=llama3
logging.level.com.llm.=DEBUG

weather.api.key=add267fa203d294888e7592af910bf9a
weather.api.url=https://api.openweathermap.org/data/2.5/weather

spring.ai.ollama.embedding.model=nomic-embed-text

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
server.port=${PORT:8080}